apiVersion: apps/v1
kind: Deployment
metadata:
  name: unstructured
  labels:
    app: unstructured
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unstructured
  template:
    metadata:
      labels:
        app: unstructured
    spec:
      containers:
      - name: unstructured
        image: unstructured
        imagePullPolicy: IfNotPresent
        command:
          - python
        args:
          - app.py
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: tmp
          mountPath: /tmp/data-mate
      volumes:
      - name: tmp
        hostPath:
          path: /tmp/data-mate

---
apiVersion: v1
kind: Service
metadata:
  name: unstructured
  labels:
    app: unstructured
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: unstructured
