services:
  deer-flow-backend:
    image: ${REGISTRY:-}deer-flow-backend
    container_name: deer-flow-backend
    env_file:
      - .env
    volumes:
      - ./conf.yaml:/app/conf.yaml:ro
      - deer-flow-log-volume:/var/log/deer-flow
    restart: unless-stopped
    networks:
      - datamate

  deer-flow-frontend:
    image: ${REGISTRY:-}deer-flow-frontend
    container_name: deer-flow-frontend
    env_file:
      - .env
    depends_on:
      - deer-flow-backend
    restart: unless-stopped
    networks:
      - datamate

volumes:
  deer-flow-log-volume:
    name: deer-flow-log-volume

networks:
  datamate:
    driver: bridge
    name: datamate-network
    external: true
