apiVersion: apps/v1
kind: Deployment
metadata:
  name: mineru
  labels:
    app: mineru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mineru
  template:
    metadata:
      labels:
        app: mineru
    spec:
      containers:
      - name: mineru
        image: mineru
        imagePullPolicy: IfNotPresent
        command:
          - mineru-api
        args:
          - --host
          - "0.0.0.0"
          - --port
          - "8000"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: tmp
          mountPath: /tmp/data-mate
      volumes:
      - name: tmp
        hostPath:
          path: /tmp/data-mate

---
apiVersion: v1
kind: Service
metadata:
  name: mineru
  labels:
    app: mineru
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: mineru
