name: Python Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/images/datamate-python/**'
      - 'runtime/datamate-python/**'
      - '.github/workflows/docker-image-backend-python.yml'
      - '.github/workflows/docker-images-reusable.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scripts/images/datamate-python/**'
      - 'runtime/datamate-python/**'
      - '.github/workflows/docker-image-backend-python.yml'
      - '.github/workflows/docker-images-reusable.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  call-docker-build:
    name: Build and Push Backend Python Docker Image
    uses: ./.github/workflows/docker-images-reusable.yml
    permissions:
      contents: read
      packages: write
    with:
      service_name: backend-python
      build_dir: .
