name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'scripts/images/backend/**'
      - '.github/workflows/docker-image-backend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'scripts/images/backend/**'
      - '.github/workflows/docker-image-backend.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  call-docker-build:
    name: Build and Push Backend Docker Image
    uses: ./.github/workflows/docker-images-reusable.yml
    permissions:
      contents: read
      packages: write
    with:
      service_name: backend
      build_dir: .
