name: Database Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/db/**'
      - 'scripts/images/database/**'
      - '.github/workflows/docker-image-database.yml'
      - '.github/workflows/docker-images-reusable.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scripts/db/**'
      - 'scripts/images/database/**'
      - '.github/workflows/docker-image-database.yml'
      - '.github/workflows/docker-images-reusable.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  call-docker-build:
    name: Build and Push Database Docker Image
    uses: ./.github/workflows/docker-images-reusable.yml
    permissions:
      contents: read
      packages: write
    with:
      service_name: database
      build_dir: .
